server:
  port: ${SERVER_PORT:8089}

spring:
  application:
    name: incidencia-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://ep-polished-moon-apxbe2xc-pooler.c-7.us-east-1.aws.neon.tech/apr_incidencia_db?sslmode=require&channel_binding=require}
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:npg_n9b1yhDLRCTN}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
